import { z } from "zod";

// Define a schema for ARIA roles
const ariaRoles = [
    "alert",
    "alertdialog",
    "application",
    "article",
    "banner",
    "button",
    "checkbox",
    "columnheader",
    "combobox",
    "complementary",
    "contentinfo",
    "definition",
    "dialog",
    "directory",
    "document",
    "feed",
    "figure",
    "form",
    "grid",
    "gridcell",
    "group",
    "heading",
    "img",
    "link",
    "list",
    "listitem",
    "listbox",
    "log",
    "main",
    "marquee",
    "math",
    "menu",
    "menubar",
    "menuitem",
    "menuitemcheckbox",
    "menuitemradio",
    "navigation",
    "none",
    "note",
    "option",
    "presentation",
    "progressbar",
    "radio",
    "radiogroup",
    "region",
    "row",
    "rowgroup",
    "rowheader",
    "scrollbar",
    "search",
    "searchbox",
    "separator",
    "slider",
    "spinbutton",
    "status",
    "switch",
    "tab",
    "table",
    "tablist",
    "tabpanel",
    "term",
    "textbox",
    "timer",
    "toolbar",
    "tooltip",
    "tree",
    "treegrid",
    "treeitem",
    // Add other ARIA roles as needed
];

const ariaSelectorSchema = z.object({
    role: z.enum(ariaRoles),
    options: z.object({
        name: z.string().optional(),
        hidden: z.boolean().optional(),
        level: z.number().optional(),
        selected: z.boolean().optional(),
        expanded: z.boolean().optional(),
        checked: z.boolean().optional(),
        pressed: z.boolean().optional(),
    }),
});

// Define the Action schema
export const actionSchema = z.discriminatedUnion("actionType", [
    z.object({
        actionType: z.enum(["hoverOver"]),
        ariaSelector: ariaSelectorSchema,
    }),
    z.object({
        actionType: z.enum(["clickOn"]),
        ariaSelector: ariaSelectorSchema,
    }),
    z.object({
        actionType: z.enum(["doubleClickOn"]),
        ariaSelector: ariaSelectorSchema,
    }),
    z.object({
        actionType: z.enum(["keyboardInputString"]),
        ariaSelector: ariaSelectorSchema,
        string: z.string(),
    }),
    z.object({
        actionType: z.enum(["keyboardInputSingleKey"]),
        ariaSelector: ariaSelectorSchema,
        key: z.string(),
    }),
    z.object({
        actionType: z.enum(["hardWait"]),
        milliseconds: z.number(),
    }),
    z.object({
        actionType: z.enum(["navigate"]),
        url: z.string().url(),
    }),
    z.object({
        actionType: z.enum(["markSpecAsFailed"]),
        explanation: z.string().max(100),
    }),
    z.object({
        actionType: z.enum(["markSpecAsPassed"]),
        explanation: z.string().max(100),
    }),
]);
